---
version: 2.1

orbs:
  executor-tools: twdps/executor-tools@5.0.0
  op: twdps/onepassword@3.0.0
  do: twdps/pipeline-events@5.1.0

globals:
  - &context platform
  - &shell op run --env-file op.env -- /bin/bash -eo pipefail

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-each-run: &on-each-run
  branches:
    only: /main/
  tags:
    only: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

command:

  set-environment:
    steps:
      - op/env
      - op/write-to-file:
          op-value: platform/svc-cosign-private-key/notesPlain
          out-file: cosign.key
      - op/write-to-file:
          op-value: platform/svc-cosign-public-key/notesPlain
          out-file: cosign.pub

workflows:

  build and publish:
    jobs:
      - executor-tools/dev-release:
          name: alpine image build
          context: *context
          shell: *shell
          dockerfile: Dockerfile.alpine
          image: twdps/circleci-infra-gcp
          tag: alpine-edge
          snyk-scan: true
          snyk-severity-threshold: high
          snyk-skip-base-image: true
          snyk-organization: twplatformlabs
          bats-test: true
          bats-entry-point: /bin/ash
          bats-test-path: test/circleci_infra_gcp.bats
          opencontainer-labels: true
          security-scan-nofail: true
          after-checkout:
            - op/env
          filters: *on-each-run

      - executor-tools/dev-release:
          name: ubuntu image build
          context: *context
          shell: *shell
          dockerfile: Dockerfile.ubuntu
          image: twdps/circleci-infra-gcp
          tag: ubuntu-edge
          snyk-scan: true
          snyk-severity-threshold: high
          snyk-skip-base-image: true
          snyk-organization: twplatformlabs
          bats-test: true
          bats-entry-point: /bin/bash
          bats-test-path: test/circleci_infra_gcp.bats
          opencontainer-labels: true
          security-scan-nofail: true
          after-checkout:
            - op/env
          filters: *on-each-run



  # release version:
  #   jobs:

  #     - executor-tools/publish:
  #         name: alpine release
  #         shell: *shell
  #         context: *context
  #         registry: *registry
  #         pull-tag: alpine-edge
  #         tag-annotation: alpine-
  #         image: twdps/circleci-infra-gcp
  #         release-tag: alpine-stable
  #         sign-image: true
  #         sbom: true
  #         after-publish:
  #           - run:
  #               name: setup cosign keys
  #               command: |
  #                 op inject -i cosign.key.env -o cosign.key
  #                 op inject -i cosign.pub.env -o cosign.pub
  #         filters: *on-tag-main

  #     - executor-tools/publish:
  #         name: slim release
  #         shell: *shell
  #         context: *context
  #         registry: *registry
  #         pull-tag: slim-edge
  #         tag-annotation: slim-
  #         image: twdps/circleci-infra-gcp
  #         release-tag: slim-stable
  #         sign-image: true
  #         sbom: true
  #         after-publish:
  #           - run:
  #               name: setup cosign keys
  #               command: |
  #                 op inject -i cosign.key.env -o cosign.key
  #                 op inject -i cosign.pub.env -o cosign.pub
  #         filters: *on-tag-main

  # release-events:
  #   jobs:
  #     - do/schedule-pipeline:
  #         name: configure weekly trigger
  #         shell: *shell
  #         context: *context
  #         scheduled-pipeline-name: weekly-ci-build
  #         scheduled-pipeline-description: |
  #           Automatically trigger image build on a weekly schedule. Failure of
  #           this recurring build indicates new releases of dependent packages.
  #         hours-of-day: "[1]"
  #         days-of-week: "[\"SUN\"]"
  #         filters: *on-tag-main

  #     - do/release:
  #         name: generate release notes
  #         shell: *shell
  #         context: *context
  #         on-tag: true
  #         filters: *on-tag-main
